## Quantun LiveProject: *Week 1*

## Workflow 3: Just enough Quantum

### Reviewer: Christian Sutton ---  christian.sutton@gmail.com 

In [1]:
import numpy as np
import qutip as q
from numpy import linalg as LA
import matplotlib.pyplot as plt
import pandas as pd

## Deliverables

Can you apply a new gate C-NOT to a two Quibit system?
`CNOT = np.array([[1,0,0,0],[0,1,0,0],[0,0,0,1],[0,0,1,0]])`

Can you do a dot multiplation of a KET and a BRA? 
∣0⟩
⟨0∣
∣0⟩⟨0∣ What do you get?

In [2]:
ket0 = np.array([[complex(1,0)],[complex(0,0)]])
ket1 = np.array([[complex(0,0)],[complex(1,0)]])

ket00 = np.kron(ket0,ket0)
ket01 = np.kron(ket0,ket1)
ket10 = np.kron(ket1,ket0)
ket11 = np.kron(ket1,ket1)

In [3]:
for i in [ket00,ket01,ket10,ket11]:
        print(i,end='\n\n')

[[1.+0.j]
 [0.+0.j]
 [0.+0.j]
 [0.+0.j]]

[[0.+0.j]
 [1.+0.j]
 [0.+0.j]
 [0.+0.j]]

[[0.+0.j]
 [0.+0.j]
 [1.+0.j]
 [0.+0.j]]

[[0.+0.j]
 [0.+0.j]
 [0.+0.j]
 [1.+0.j]]



In [4]:
CNOT = np.array([[1,0,0,0],[0,1,0,0],[0,0,0,1],[0,0,1,0]])
CNOT.shape

(4, 4)

In [5]:
CNOT @ ket11

array([[0.+0.j],
       [0.+0.j],
       [1.+0.j],
       [0.+0.j]])

In [6]:
for i in [ket00,ket01,ket10,ket11]:
    #print(f'CNOT dot {i})\n')
    print(CNOT @ i)
    print('-----')

[[1.+0.j]
 [0.+0.j]
 [0.+0.j]
 [0.+0.j]]
-----
[[0.+0.j]
 [1.+0.j]
 [0.+0.j]
 [0.+0.j]]
-----
[[0.+0.j]
 [0.+0.j]
 [0.+0.j]
 [1.+0.j]]
-----
[[0.+0.j]
 [0.+0.j]
 [1.+0.j]
 [0.+0.j]]
-----


In [7]:
c = 1/np.sqrt(2)
ket = np.array([[complex(c,0)],[complex(c,0)]])
bra = ket.T.conj()

In [8]:
ket @ bra

array([[0.5+0.j, 0.5+0.j],
       [0.5+0.j, 0.5+0.j]])

In [9]:
ket

array([[0.70710678+0.j],
       [0.70710678+0.j]])

In [10]:
ket.shape

(2, 1)

In [11]:
bra

array([[0.70710678-0.j, 0.70710678-0.j]])

In [12]:
bra.shape

(1, 2)